ALL_MAKES = [
    'Aaen',
    'AAR',
    'Abell',
    'Abako',
    'ABC',
    'ABC',
    'ABC',
    'ABC',
    'Abbotsford',
    'Abendsonne',
    'Aberdale',
    'Abe-Star',
    'Abingdon',
    'ABJ',
    'ACE Motorcycles',
    'Achilles',
    'Achilles',
    'Ackland',
    'Acme',
    'Acme Motorcycles',
    'ADB',
    'Ader',
    'Adler',
    'Adly',
    'Adma',
    'Adriatica',
    'Advance',
    'AEL',
    'Aeolus',
    'Aeon',
    'AER',
    'Aermacchi',
    'Aero',
    'AGF',
    'Agrale',
    'Agrati',
    'Airman',
    'Airmoto',
    'Airolite',
    'Ajax',
    'AJP',
    'AJR',
    'AJS',
    'AJW',
    'AKD',
    'Akkens',
    'Alba',
    'Albertus',
    'Alcyon',
    'Alecto',
    'Alert',
    'Alfer',
    'Algat',
    'Alp',
    'Alpino',
    'Alldays',
    'Alligator',
    'Allon',
    'Allright',
    'Allstate',
    'AMAG',
    'Amag',
    'Amazonas',
    'Ambassador',
    'Ambra',
    'AMC',
    'AMC',
    '1918 America',
    'America',
    'American',
    'American',
    'American Dirt Bike',
    'American Eagle',
    'American Eagle',
    'American Iron Horse',
    'American King V',
    'American Quantum',
    'American Rocket',
    'American X',
    'AMI',
    'Ammon',
    'AMO',
    'AMS',
    'Ancilotti',
    'Andrees',
    'Anker',
    'Anthony',
    'Anzani',
    'Anzani',
    'A.P. USA',
    'Apache',
    'Apfelbeck',
    'Apollo',
    'Aprilia',
    'AR',
    'Arbinet',
    'Arco',
    'Ardie',
    'Argeo',
    'Argyle',
    'Ariel',
    'Aristos',
    'Armac',
    'Armstrong',
    'Arno',
    'Arrow',
    'Arrow',
    'Ascot',
    'Ascot Pullin',
    'ASL',
    'Aspes',
    'Astoria',
    'Astra',
    'Atala',
    'Atco',
    'ATK',
    'Atlantic',
    'Atomette',
    'Auranthetic',
    'Aurora',
    'Aurora',
    'Aussi',
    'Austin',
    'Austria',
    'Austro-Motorette',
    'Auto-Bi',
    'Auto-Bike',
    'Auto Car',
    'Auto Cycle',
    'Autocylette',
    'Autoette',
    'Autoflug',
    'Autoglide',
    'Autoglider',
    'Autoped',
    'Auto-Fauteuil',
    'AutoMoto',
    'Avanti',
    'Avenger',
    'AVG',
    'AWO',
    'Babetta',
    'BAC',
    'Badger',
    'Baier',
    'Bajaj',
    'Bakker',
    'BAM',
    'Barb',
    'Barigo',
    'Barnsley',
    'Barr',
    'Bartali',
    'Bastert',
    'Bat',
    'Batavus',
    'Battey',
    'Bayern',
    'Bayley Flyer',
    'B&D',
    'Beard & Able',
    'Beare',
    'Beau Ideal',
    'Be-Be',
    'Beeston',
    'Bellini',
    'Benelli',
    'Bercley',
    'Bergfex',
    'Berini',
    'Bernadet',
    'Beta',
    'BFG',
    'Bianchi',
    'Bi-Auto-Go',
    'Bi-Car',
    'Big Brute',
    'Big Buffalo',
    'Big Dog',
    'Binks',
    'Bismarck',
    'Bleha',
    'BMW',
    'Boar',
    'Boge',
    'Bohme',
    'Bohmerland',
    'Boisselot',
    'Bond',
    'Boom Trikes',
    'Borile',
    'Boss Hoss',
    'Bourget',
    'Bovy',
    'Bowman',
    'Bown',
    'Boxer',
    'Blackburne',
    'Blake',
    'Blata',
    'Bleha',
    'Blucher',
    'Blue Bird',
    'BM',
    'Bohme',
    'Bombardier',
    'Borile',
    'Bradbury',
    'Brand',
    'Brandenburg',
    'Breeze',
    'Brennabor',
    'Bridgestone',
    'Briggs-Stratton',
    'Britten',
    'Brondoit',
    'Brough-Superior',
    'Brown',
    'B&S',
    'BSA',
    'BSA Regal',
    'Bucker',
    'Buell',
    'Buffalo',
    'Bull Dog',
    'Bullock',
    'Bultaco',
    'Butler Petrol-Cycle',
    'Butterfield',
    'Cabri',
    'Cabton',
    'Cagiva',
    'Califfo',
    'California',
    'Capriolo',
    'Calthorpe',
    'CanAm',
    'Canda',
    'Cannondale',
    'Caproni',
    'Carabella',
    'Casal',
    'CCM',
    'CCM',
    'Cemec',
    'Centaur',
    'Century',
    'CF',
    'Champion',
    'Champion',
    'Chater Lea',
    'Chell',
    'Chiorda',
    'Cimatti',
    'Clement',
    'Cleveland',
    'Cleveland',
    'Cleveland',
    'Clyno',
    'Cnopm',
    'Cobra',
    'Cockerell',
    'Comet',
    'Comet',
    'Commander',
    'Condor',
    'Confederate',
    'Copeland Steam Motorcycle',
    'Corgi',
    'Coronet',
    'Cossack',
    'Cotton',
    'Coventry-Eagle',
    'Coventry-Victor',
    'CPI',
    'CP-Roleo',
    'Crawford',
    'Crescent',
    'Crocker',
    'Crosley',
    'Crouch',
    'Cesepel',
    'Cucciolo',
    'Curtiss',
    'Cushman',
    'CWS',
    'Cyc-Auto',
    'Cyclemaster',
    'Cyclemoto',
    'Cyclemotor',
    'Cycles Delight',
    'Cyclone',
    'Cyclone',
    'Cyclone',
    'Cyril Huze',
    'CZ',
    'Daelim',
    'Daihatsu',
    'Daimler',
    'Dalesman',
    'Dandy',
    'Day',
    'DayStar',
    'Dayton',
    'Dayton',
    'De Dion Bouton',
    'Della Ferrera',
    'DeLong',
    'De Luxe',
    'DeLuxe',
    'Demm',
    'Denali',
    'Derbi',
    'Desperado',
    'Diamant',
    'Diamond',
    'Di Blasi',
    'Didik',
    'D.K.R.',
    'DKW',
    'D.M.W.',
    'Dnepr',
    'Dolf',
    'Doodlebug',
    'Dot',
    'Douglas',
    'D-Rad',
    'Dream Toki',
    'Driver',
    'Drysdale',
    'DS Malterre',
    'Duck',
    'Duesenberg',
    'Ducati',
    'Dufaux',
    'Dukelow',
    'Dunstall',
    'Durandal',
    'Durkopp',
    'Duzmo',
    'Dynacycle',
    'Eagle',
    'EBS',
    'Ecomobile',
    'Economy',
    'Ecstasy',
    'eCycle',
    'Edmond',
    'E&F',
    'Egli',
    'Electra',
    'Electrobike',
    'Elf',
    'Elf',
    'Elswick',
    'Emblem',
    'EMC',
    'Erie',
    'Esarati',
    'ESO',
    'Esse',
    'E-Ton',
    'Evans',
    'Excelsior',
    'Excelsior',
    'Excelsior',
    'Excelsior Henderson',
    'Exile Cycles',
    'Express',
    'Eysink',
    'Fabianski',
    'Fafnir',
    'Fairy',
    'Fantic',
    'Far',
    'Farmbyke',
    'Farron',
    'Favorit',
    'FB-AJS',
    'Federation/Federal',
    'Feilbach Limited',
    'Ferbedo',
    'Ferrari',
    'FKS',
    'Fichtel & Sachs',
    'Flanders',
    'Flandria',
    'Fleming',
    'Flying Merkel',
    'Flink',
    'FN',
    'Francis-Barnett',
    'Frera',
    'Freras',
    'Freyer & Miller',
    'Freze',
    'FSO',
    'Force',
    'Fowler Four',
    'Fowler Manson-Sherman',
    'Foxinette',
    'Francke-Johannsmeyer',
    'Franklin',
    'Fuki Planning',
    'Gambler',
    'Garelli',
    'Gazelle',
    'GD',
    'Gearless',
    'Geco-Herstal',
    'Geer',
    'Gem MiniMoto',
    'Gemini',
    'Geneva',
    'Gerhart Four',
    'Gerkinet',
    'Germaan',
    'Gerosa',
    'G&G',
    'Ghezzi & Brian',
    'Giggle',
    'Gilera',
    'Gillet-Herstal',
    'Gitan',
    'Glas-Goggo',
    'Globester',
    'GM',
    'Gnome Rhone',
    'Godden',
    'Goericke',
    'Gough',
    'GrcMoto',
    'Greeves',
    'Greyhound',
    'Greyhound',
    'Griffon',
    'Grindlay',
    'Gripen',
    'HADC',
    'Haggo',
    'Haleson',
    'Hampden',
    'Harley',
    'Harley-Davidson',
    'Harper',
    'Harper',
    'Harris',
    'Hartford',
    'Hausmann',
    'Haverford',
    'Haveloc',
    'Hawker',
    'Hawthorne',
    'HB',
    'Healing',
    'Heavy Duty',
    'Hec',
    'Hec',
    'Hecker',
    'Hedlund',
    'Hedstrom',
    'Heinkel',
    'Helios',
    'Henderson',
    'Hemingway',
    'Herring',
    'Hercules',
    'Hercules',
    'Hercules W2000',
    'Hercules',
    'Hero',
    'Hesketh',
    'H&G',
    'H & H',
    'Highland',
    'Hilaman',
    'Hildebrand and Wolfmuller',
    'Hobart',
    'Hodaka',
    'Holden Motor Bicycle',
    'Holley',
    'Horex',
    'Honda',
    'HRD',
    'Hudson',
    'Humber',
    'Hummel',
    'Hummer',
    'Hunwick Hallam',
    'Hunwick Harrop',
    'Hurley-Pugh',
    'Hurricane',
    'Husaberg',
    'Husqvarna',
    'Huy',
    'Hyosung',
    'Ideal Jawa',
    'IKH',
    'ILO',
    'Imperia',
    'Imperial',
    'Indian',
    'Indian Enfield',
    'Industrial',
    'Invincible',
    'Irbit',
    'Island Hopper',
    'Italemmezeta',
    'ItalJet',
    'Italvel',
    'Iver-Johnson',
    'IWL',
    'Ixion',
    'Izh/Planata',
    'Izh',
    'JAC',
    'James',
    'James A Smith',
    'Jamathi',
    'JAP',
    'Jawa',
    'JB Special',
    'Jeepette',
    'Jefferson',
    'Jewel',
    'Jincheng',
    'Jing Shing',
    'Joerns',
    'Johnson Motowheel',
    'Johnson',
    'JOLI',
    'Jordan',
    'Juckes',
    'Junak',
    'Junior',
    'Kaestner',
    'Kahena',
    'Kane Pennington',
    'Kannon',
    'Kasea',
    'Kanuni',
    'Kawasaki',
    'Keating',
    'Kendal',
    'Kenilworth',
    'Kent',
    'Kenzler-Waverly',
    'Kerry',
    'Kettenkrad',
    'Kiefler',
    'Kievlyanin',
    'KillaCycle',
    'Kinetic',
    'Kirby Special',
    'Kirkham',
    'KMZ',
    'Kobas',
    'Kodiak',
    'Koehler Escoffier',
    'Kokomo',
    'Komar',
    'Kossm',
    'Kramit',
    'Krauser',
    'Kreidler',
    'Kreidler Florett',
    'KTM',
    'Kulture',
    'Kumoto',
    'Kurier',
    'Kymco',
    'Lady',
    'La Foudre',
    'La Mondiale',
    'La Ray',
    'Laurin and Klement',
    'Laverda',
    'Lea Francis',
    'LDE',
    'Lech',
    'Lectraa',
    'LEM',
    'Leopard',
    'Levis',
    'Lewis',
    'Light Thor-Bred',
    'Lightning',
    'Lilac',
    'Lincoln Elk',
    'Linto',
    'Lion-Rapide',
    'Lito',
    'Little Giant',
    'LLoyde',
    'Lohner',
    'Lomart',
    'Long',
    'Lot',
    'Lucznik',
    'Mabeco',
    'MAG',
    'Maico',
    'Maico',
    'Majestic',
    'Majestic',
    'Malaguti',
    'Malanca',
    'Maltby',
    'Malvern Star',
    'Manco',
    'Manet',
    'Manson',
    'Mars',
    'Mars',
    'Marsh',
    'Martinsyde',
    'Marusho',
    'Marvel',
    'Mas',
    'Matchless',
    'Mazzilli',
    'MB',
    'MBK',
    'MBS',
    'MCC',
    'McEvoy',
    'McKenzie',
    'Meadowbrook',
    'Mears',
    'Mega',
    'Megola',
    'Meier BAC',
    'Meguro',
    'Meray',
    'Mercier',
    'Mercury',
    'Merkel',
    'Merkel Motor Wheel',
    'Mesco',
    'Metz',
    'M.G.C.',
    'MGC',
    'Miami',
    'Michaelson',
    'Michaux-Perreaux Steam Velocipede',
    'Micro-Machine',
    'Midget Bicar',
    'Midual',
    'Miele',
    'Militaire',
    'Militor',
    'Miller',
    'Minarelli',
    'Minerva',
    'Mini-Motor',
    'Minneapolis',
    'Minsk',
    'Mirage',
    'Mival',
    'MM',
    'Mobylette',
    'Modenas',
    'Moj',
    'Monarch',
    'Monark',
    'Mon-Auto',
    'Mondial',
    'Monet-Goyon',
    'Montgomery',
    'Montgomery-Ward',
    'Montesa',
    'Monotrace',
    'Moore',
    'Morbidelli',
    'Morgan',
    'Morgan',
    'Morini',
    'Morini Mezetti',
    'Morris-Corkhill',
    'Moser',
    'Moskva',
    'Mostyn',
    'Moto B',
    'Motobecane',
    'MotoBi',
    'Motoconfort',
    'Moto Gori',
    'Moto Guzzi',
    'Motom',
    'Moto Martin',
    'Moto Morini',
    'Motopede',
    'Moto-Reve',
    'Motosacoche',
    'Mototrans',
    'Moto-villa',
    'M-Star',
    'Munch',
    'Mustang',
    'MuZ',
    'MV Agusta',
    'MZ',
    'Narcisse',
    'Nelk',
    'Neracar',
    'New Courier',
    'New Era',
    'New Hudson',
    'New Imperial',
    'Niemen',
    'Nimbus',
    'Nioga',
    'NMI',
    'Norman',
    'Norsman',
    'Norton',
    'NSU',
    'NSU',
    'NUT',
    'Nut',
    'NVT',
    'Nzeta',
    'Oakes',
    'OD',
    'OEC',
    'OK',
    'Okay',
    'OK-Supreme',
    'Olympic',
    'Olympus',
    'Omega',
    'Opel',
    'Orbit',
    'Orient',
    'Orionette',
    'Orle',
    'Oscar',
    'Oscar',
    'Ossa',
    'Over',
    'Oz',
    'Pacer',
    'Paloma',
    'Pam',
    'Pansy',
    'Panther',
    'Panther',
    'Panzer',
    'Parkyns-Bateman',
    'Parilla',
    'Patee',
    'Paton',
    'Patria',
    'Pedigree',
    'Peerless',
    'Peerless',
    'Peerless',
    'PEM',
    'Pen Nib',
    'Pennington',
    'Penton',
    'Peraves',
    'Perkun',
    'Peugeot',
    'PGO',
    'Phoenix',
    'Phoenix',
    'Phoenix',
    'Piaggio',
    'Piatti',
    'Pierce',
    'Pigon',
    'Pioneer',
    'Pirate',
    'P&M',
    'PMZ',
    'Podkow',
    'Pointer',
    'Polaris',
    'Polini',
    'Pope',
    'Powell',
    'P&P',
    'Praga',
    'Premier',
    'Precision',
    'Pro 1',
    'Promot',
    'P-T USA',
    'Puch',
    'PZInz',
    'Quadrant',
    'Quantel',
    'Quasar',
    'Rabbit',
    'Rabiniek',
    'Radior',
    'Radco',
    'Rambler',
    'Ratier',
    'Reading Standard',
    'Racycle',
    'Raleigh',
    'Raynal',
    'Ready',
    'Red Horse',
    'Regas',
    'Regina',
    'Reliance',
    'Rene-Gillet',
    'Rex',
    'Reynolds Special',
    'R&H',
    'Rickman',
    'Ridley',
    'Riedel',
    'Rieju',
    'Rieju',
    'Rikuo',
    'Riley',
    'Riotte',
    'Rizzato',
    'Robinson',
    'Roc',
    'Rockford',
    'Roehr',
    'Rokon',
    'Roland',
    'Rollaway',
    'Romet',
    'Roper',
    'Roper',
    'Rossija',
    'Rotax',
    'Roto',
    'Roton',
    'Roussey',
    'Royal Enfield',
    'Enfield India',
    'Rover',
    'Rovena',
    'RTX',
    'Rudge',
    'Rugmobile',
    'Rumi',
    'Rush',
    'Rys',
    'Sachs',
    'Sadran',
    'Salsbury',
    'Sarolea',
    'Sampson',
    'Sanglas',
    'Sanyang',
    'Sar',
    'Sar',
    'Saxonette',
    'SBM',
    'Schickel',
    'Schliha',
    'Schuttoff',
    'Scootamota',
    'Scorpa',
    'Scott',
    'SD',
    'Sears',
    'Seeley',
    'Segale',
    'Sertum',
    'SFM',
    'Shacklock',
    'Shang Wei',
    'Shaw',
    'She-Lung',
    'Sherco',
    'Shin-Meiwa',
    'Shin San Tong',
    'SHL',
    'Silk',
    'Silver Pigeon',
    'Simo',
    'Simplex',
    'Simplex',
    'Simpson',
    'Sinclair',
    'Singa',
    'Singer',
    'Skootmobile',
    'Skipee',
    'SM',
    'Smart',
    'Smith Motor Wheel',
    'Snell',
    'Snob',
    'Sojuz',
    'Sokol',
    'Solex',
    'Solvay',
    'Spacke',
    'Spagthorpe',
    'Sparkbrook',
    'Sparta',
    'Sprite',
    'Spondon',
    'Standard',
    'Stanger',
    'Star',
    'Star-Griffon',
    'Stearns',
    'Steed',
    'Steffey',
    'Stellar',
    'Stevens',
    'Stewart',
    'Stock',
    'Stratton',
    'Stricker',
    'Stylson',
    'Styria',
    'Suddard',
    'Sundiro',
    'Sun',
    'Sun',
    'Sunbeam',
    'Superia',
    'Super-X',
    'Suzuki',
    'Svalan',
    'SVM',
    'SWM',
    'Tami',
    'Tas',
    'Tatran',
    'Teco',
    'Temple',
    'Terrot',
    'Testi',
    'TGB',
    'TGM',
    'Theim',
    'Thomas',
    'Thor',
    'Thoroughbred',
    'Three Spires',
    'Thumpstar',
    'Tiger',
    'Tiger',
    'Tiger',
    'Tinkham',
    'TIZ',
    'Titan',
    'Tohatsu',
    'Tomos',
    'Topper',
    'Tornax',
    'Tornedo',
    'Tote Gote',
    'Tourist',
    'Torpedo',
    'Toyomotor',
    'Trenton',
    'TriKing',
    'Trimoto',
    'Triumph',
    'Traumannsdorf',
    'Tula',
    'Tule Trooper',
    'TVS',
    'Twin Eagle',
    'TWN',
    'Ultra',
    'Ural',
    'URS',
    'V-8',
    'Van Veen',
    'Vauxhall',
    'Vee Two',
    'Velocette',
    'Velocipedraisiavaporianna',
    'Veremati',
    'Verhovina',
    'Vespa',
    'Victoria',
    'Victory',
    'Villa',
    'Villiers',
    'Villof',
    'Vincent-HRD',
    'Vis Fabrik',
    'Vneemotoprom',
    'Vogelbilt',
    'Voloci',
    'Vor',
    'Voskhod',
    'Voxan',
    'Wabo',
    'Wagner',
    'Wall',
    'Walter',
    'Wanderer',
    'Waratah',
    'Wasp',
    'Waverly',
    'Welbike',
    'Wendax',
    'Werner',
    'West Coast Choppers',
    'Westlake',
    'WFM',
    'Whipple',
    'Whiting',
    'Whizzer',
    'Widmayer',
    'Wild West Motor Company',
    'Wilkinson',
    'Williams',
    'Williamson',
    'Winged Wheel',
    'Wisconsin Wheel',
    'Wolf',
    'Wood',
    'Woods-Meagher',
    'Wooler',
    'WSK',
    'Wulfruna',
    'Wul-Gum',
    'Wysecycle',
    'Xingfu',
    'Yale',
    'Yale-California',
    'Yamaguchi',
    'Yamaha',
    'Yankee',
    'Yankee',
    'Yankee',
    'Yezdi',
    'Young Rider',
    'Zanzani',
    'Zap',
    'Zehnder',
    'Zenith',
    'ZID',
    'ZipCycle',
    'Zuch',
    'Zundapp',
    'ZSS',
    'ZZR'
]

US_STATES = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

URLS_USA = {    # 444 unique locations
     # "AK": [
     #  "https://anchorage.craigslist.org",
     #  "https://fairbanks.craigslist.org",
     #  "https://kenai.craigslist.org",
     #  "https://juneau.craigslist.org"
     # ],
     # "AL": [
     #  "https://auburn.craigslist.org",
     #  "https://bham.craigslist.org",
     #  "https://columbusga.craigslist.org",
     #  "https://dothan.craigslist.org",
     #  "https://shoals.craigslist.org",
     #  "https://gadsden.craigslist.org",
     #  "https://huntsville.craigslist.org",
     #  "https://mobile.craigslist.org",
     #  "https://montgomery.craigslist.org",
     #  "https://tuscaloosa.craigslist.org"
     # ],
     "AR": [
      "https://fayar.craigslist.org",
      "https://fortsmith.craigslist.org",
      "https://jonesboro.craigslist.org",
      "https://littlerock.craigslist.org",
      "https://memphis.craigslist.org",
      "https://texarkana.craigslist.org"
     ],
     "AZ": [
      "https://flagstaff.craigslist.org",
      "https://mohave.craigslist.org",
      "https://phoenix.craigslist.org",
      "https://prescott.craigslist.org",
      "https://showlow.craigslist.org",
      "https://sierravista.craigslist.org",
      "https://tucson.craigslist.org",
      "https://yuma.craigslist.org"
     ],
     # "CA": [
     #  "https://bakersfield.craigslist.org",
     #  "https://chico.craigslist.org",
     #  "https://fresno.craigslist.org",
     #  "https://goldcountry.craigslist.org",
     #  "https://hanford.craigslist.org",
     #  "https://humboldt.craigslist.org",
     #  "https://imperial.craigslist.org",
     #  "https://inlandempire.craigslist.org",
     #  "https://losangeles.craigslist.org",
     #  "https://mendocino.craigslist.org",
     #  "https://merced.craigslist.org",
     #  "https://modesto.craigslist.org",
     #  "https://monterey.craigslist.org",
     #  "https://orangecounty.craigslist.org",
     #  "https://palmsprings.craigslist.org",
     #  "https://redding.craigslist.org",
     #  "https://reno.craigslist.org",
     #  "https://sacramento.craigslist.org",
     #  "https://sandiego.craigslist.org",
     #  "https://slo.craigslist.org",
     #  "https://santabarbara.craigslist.org",
     #  "https://santamaria.craigslist.org",
     #  "https://sfbay.craigslist.org",
     #  "https://siskiyou.craigslist.org",
     #  "https://stockton.craigslist.org",
     #  "https://susanville.craigslist.org",
     #  "https://ventura.craigslist.org",
     #  "https://visalia.craigslist.org",
     #  "https://yubasutter.craigslist.org"
     # ],
     # "CO": [
     #  "https://boulder.craigslist.org",
     #  "https://cosprings.craigslist.org",
     #  "https://denver.craigslist.org",
     #  "https://eastco.craigslist.org",
     #  "https://fortcollins.craigslist.org",
     #  "https://rockies.craigslist.org",
     #  "https://pueblo.craigslist.org",
     #  "https://westslope.craigslist.org"
     # ],
     # "CT": [
     #  "https://newlondon.craigslist.org",
     #  "https://hartford.craigslist.org",
     #  "https://newhaven.craigslist.org",
     #  "https://nwct.craigslist.org",
     #  "https://newyork.craigslist.org/fct/"
     # ],
     # "DE": [
     #  "https://delaware.craigslist.org/"
     # ],
     # "FL": [
     #  "https://daytona.craigslist.org",
     #  "https://keys.craigslist.org",
     #  "https://fortmyers.craigslist.org",
     #  "https://gainesville.craigslist.org",
     #  "https://cfl.craigslist.org",
     #  "https://jacksonville.craigslist.org",
     #  "https://lakeland.craigslist.org",
     #  "https://lakecity.craigslist.org",
     #  "https://ocala.craigslist.org",
     #  "https://okaloosa.craigslist.org",
     #  "https://orlando.craigslist.org",
     #  "https://panamacity.craigslist.org",
     #  "https://pensacola.craigslist.org",
     #  "https://sarasota.craigslist.org",
     #  "https://miami.craigslist.org",
     #  "https://spacecoast.craigslist.org",
     #  "https://staugustine.craigslist.org",
     #  "https://tallahassee.craigslist.org",
     #  "https://tampa.craigslist.org",
     #  "https://treasure.craigslist.org"
     # ],
     # "GA": [
     #  "https://albanyga.craigslist.org",
     #  "https://athensga.craigslist.org",
     #  "https://atlanta.craigslist.org",
     #  "https://augusta.craigslist.org",
     #  "https://brunswick.craigslist.org",
     #  "https://columbusga.craigslist.org",
     #  "https://macon.craigslist.org",
     #  "https://nwga.craigslist.org",
     #  "https://savannah.craigslist.org",
     #  "https://statesboro.craigslist.org",
     #  "https://valdosta.craigslist.org"
     # ],
     # "HI": [
     #  "https://honolulu.craigslist.org/"
     # ],
     # "IA": [
     #  "https://ames.craigslist.org",
     #  "https://cedarrapids.craigslist.org",
     #  "https://desmoines.craigslist.org",
     #  "https://dubuque.craigslist.org",
     #  "https://fortdodge.craigslist.org",
     #  "https://iowacity.craigslist.org",
     #  "https://masoncity.craigslist.org",
     #  "https://omaha.craigslist.org",
     #  "https://quadcities.craigslist.org",
     #  "https://siouxcity.craigslist.org",
     #  "https://ottumwa.craigslist.org",
     #  "https://waterloo.craigslist.org"
     # ],
     # "ID": [
     #  "https://boise.craigslist.org",
     #  "https://eastidaho.craigslist.org",
     #  "https://lewiston.craigslist.org",
     #  "https://pullman.craigslist.org",
     #  "https://spokane.craigslist.org",
     #  "https://twinfalls.craigslist.org"
     # ],
     # "IL": [
     #  "https://bn.craigslist.org",
     #  "https://chambana.craigslist.org",
     #  "https://chicago.craigslist.org",
     #  "https://decatur.craigslist.org",
     #  "https://lasalle.craigslist.org",
     #  "https://mattoon.craigslist.org",
     #  "https://peoria.craigslist.org",
     #  "https://quadcities.craigslist.org",
     #  "https://rockford.craigslist.org",
     #  "https://carbondale.craigslist.org",
     #  "https://springfieldil.craigslist.org",
     #  "https://stlouis.craigslist.org",
     #  "https://quincy.craigslist.org"
     # ],
     # "IN": [
     #  "https://bloomington.craigslist.org",
     #  "https://evansville.craigslist.org",
     #  "https://fortwayne.craigslist.org",
     #  "https://indianapolis.craigslist.org",
     #  "https://kokomo.craigslist.org",
     #  "https://tippecanoe.craigslist.org",
     #  "https://muncie.craigslist.org",
     #  "https://richmondin.craigslist.org",
     #  "https://southbend.craigslist.org",
     #  "https://terrehaute.craigslist.org",
     #  "https://chicago.craigslist.org/nwi/"
     # ],
     # "KS": [
     #  "https://kansascity.craigslist.org",
     #  "https://lawrence.craigslist.org",
     #  "https://ksu.craigslist.org",
     #  "https://nwks.craigslist.org",
     #  "https://salina.craigslist.org",
     #  "https://seks.craigslist.org",
     #  "https://swks.craigslist.org",
     #  "https://topeka.craigslist.org",
     #  "https://wichita.craigslist.org"
     # ],
     # "KY": [
     #  "https://bgky.craigslist.org",
     #  "https://cincinnati.craigslist.org",
     #  "https://eastky.craigslist.org",
     #  "https://huntington.craigslist.org",
     #  "https://lexington.craigslist.org",
     #  "https://louisville.craigslist.org",
     #  "https://owensboro.craigslist.org",
     #  "https://westky.craigslist.org"
     # ],
     # "LA": [
     #  "https://batonrouge.craigslist.org",
     #  "https://cenla.craigslist.org",
     #  "https://houma.craigslist.org",
     #  "https://lafayette.craigslist.org",
     #  "https://lakecharles.craigslist.org",
     #  "https://monroe.craigslist.org",
     #  "https://neworleans.craigslist.org",
     #  "https://shreveport.craigslist.org"
     # ],
     # "MA": [
     #  "https://boston.craigslist.org",
     #  "https://capecod.craigslist.org",
     #  "https://southcoast.craigslist.org",
     #  "https://westernmass.craigslist.org",
     #  "https://worcester.craigslist.org"
     # ],
     # "MD": [
     #  "https://annapolis.craigslist.org",
     #  "https://baltimore.craigslist.org",
     #  "https://chambersburg.craigslist.org",
     #  "https://easternshore.craigslist.org",
     #  "https://frederick.craigslist.org",
     #  "https://smd.craigslist.org",
     #  "https://westmd.craigslist.org",
     #  "https://washingtondc.craigslist.org/mld/"
     # ],
     # "ME": [
     #  "https://maine.craigslist.org/"
     # ],
     # "MI": [
     #  "https://annarbor.craigslist.org",
     #  "https://battlecreek.craigslist.org",
     #  "https://centralmich.craigslist.org",
     #  "https://detroit.craigslist.org",
     #  "https://flint.craigslist.org",
     #  "https://grandrapids.craigslist.org",
     #  "https://holland.craigslist.org",
     #  "https://jxn.craigslist.org",
     #  "https://kalamazoo.craigslist.org",
     #  "https://lansing.craigslist.org",
     #  "https://monroemi.craigslist.org",
     #  "https://muskegon.craigslist.org",
     #  "https://nmi.craigslist.org",
     #  "https://porthuron.craigslist.org",
     #  "https://saginaw.craigslist.org",
     #  "https://southbend.craigslist.org",
     #  "https://swmi.craigslist.org",
     #  "https://thumb.craigslist.org",
     #  "https://up.craigslist.org"
     # ],
     # "MN": [
     #  "https://bemidji.craigslist.org",
     #  "https://brainerd.craigslist.org",
     #  "https://duluth.craigslist.org",
     #  "https://fargo.craigslist.org",
     #  "https://mankato.craigslist.org",
     #  "https://minneapolis.craigslist.org",
     #  "https://rmn.craigslist.org",
     #  "https://marshall.craigslist.org",
     #  "https://stcloud.craigslist.org"
     # ],
     # "MO": [
     #  "https://columbiamo.craigslist.org",
     #  "https://joplin.craigslist.org",
     #  "https://kansascity.craigslist.org",
     #  "https://kirksville.craigslist.org",
     #  "https://loz.craigslist.org",
     #  "https://semo.craigslist.org",
     #  "https://springfield.craigslist.org",
     #  "https://stjoseph.craigslist.org",
     #  "https://stlouis.craigslist.org"
     # ],
     # "MS": [
     #  "https://gulfport.craigslist.org",
     #  "https://hattiesburg.craigslist.org",
     #  "https://jackson.craigslist.org",
     #  "https://memphis.craigslist.org",
     #  "https://meridian.craigslist.org",
     #  "https://northmiss.craigslist.org",
     #  "https://natchez.craigslist.org"
     # ],
     # "MT": [
     #  "https://billings.craigslist.org",
     #  "https://bozeman.craigslist.org",
     #  "https://butte.craigslist.org",
     #  "https://montana.craigslist.org",
     #  "https://greatfalls.craigslist.org",
     #  "https://helena.craigslist.org",
     #  "https://kalispell.craigslist.org",
     #  "https://missoula.craigslist.org"
     # ],
     # "NC": [
     #  "https://asheville.craigslist.org",
     #  "https://boone.craigslist.org",
     #  "https://charlotte.craigslist.org",
     #  "https://eastnc.craigslist.org",
     #  "https://fayetteville.craigslist.org",
     #  "https://greensboro.craigslist.org",
     #  "https://hickory.craigslist.org",
     #  "https://onslow.craigslist.org",
     #  "https://outerbanks.craigslist.org",
     #  "https://raleigh.craigslist.org",
     #  "https://wilmington.craigslist.org",
     #  "https://winstonsalem.craigslist.org"
     # ],
     # "ND": [
     #  "https://bismarck.craigslist.org",
     #  "https://fargo.craigslist.org",
     #  "https://grandforks.craigslist.org",
     #  "https://nd.craigslist.org"
     # ],
     # "NE": [
     #  "https://grandisland.craigslist.org",
     #  "https://lincoln.craigslist.org",
     #  "https://northplatte.craigslist.org",
     #  "https://omaha.craigslist.org",
     #  "https://scottsbluff.craigslist.org",
     #  "https://siouxcity.craigslist.org"
     # ],
     # "NH": [
     #  "https://nh.craigslist.org/"
     # ],
     # "NJ": [
     #  "https://cnj.craigslist.org",
     #  "https://jerseyshore.craigslist.org",
     #  "https://newjersey.craigslist.org",
     #  "https://southjersey.craigslist.org",
     #  "https://newyork.craigslist.org/jsy/"
     # ],
     # "NM": [
     #  "https://albuquerque.craigslist.org",
     #  "https://clovis.craigslist.org",
     #  "https://farmington.craigslist.org",
     #  "https://lascruces.craigslist.org",
     #  "https://roswell.craigslist.org",
     #  "https://santafe.craigslist.org"
     # ],
     # "NV": [
     #  "https://elko.craigslist.org",
     #  "https://lasvegas.craigslist.org",
     #  "https://reno.craigslist.org"
     # ],
     # "NY": [
     #  "https://albany.craigslist.org",
     #  "https://binghamton.craigslist.org",
     #  "https://buffalo.craigslist.org",
     #  "https://catskills.craigslist.org",
     #  "https://chautauqua.craigslist.org",
     #  "https://elmira.craigslist.org",
     #  "https://fingerlakes.craigslist.org",
     #  "https://glensfalls.craigslist.org",
     #  "https://hudsonvalley.craigslist.org",
     #  "https://ithaca.craigslist.org",
     #  "https://longisland.craigslist.org",
     #  "https://newyork.craigslist.org",
     #  "https://oneonta.craigslist.org",
     #  "https://plattsburgh.craigslist.org",
     #  "https://potsdam.craigslist.org",
     #  "https://rochester.craigslist.org",
     #  "https://syracuse.craigslist.org",
     #  "https://twintiers.craigslist.org",
     #  "https://utica.craigslist.org",
     #  "https://watertown.craigslist.org"
     # ],
     # "OH": [
     #  "https://akroncanton.craigslist.org",
     #  "https://ashtabula.craigslist.org",
     #  "https://athensohio.craigslist.org",
     #  "https://chillicothe.craigslist.org",
     #  "https://cincinnati.craigslist.org",
     #  "https://cleveland.craigslist.org",
     #  "https://columbus.craigslist.org",
     #  "https://dayton.craigslist.org",
     #  "https://huntington.craigslist.org",
     #  "https://limaohio.craigslist.org",
     #  "https://mansfield.craigslist.org",
     #  "https://wheeling.craigslist.org",
     #  "https://parkersburg.craigslist.org",
     #  "https://sandusky.craigslist.org",
     #  "https://toledo.craigslist.org",
     #  "https://tuscarawas.craigslist.org",
     #  "https://youngstown.craigslist.org",
     #  "https://zanesville.craigslist.org"
     # ],
     # "OK": [
     #  "https://fortsmith.craigslist.org",
     #  "https://lawton.craigslist.org",
     #  "https://enid.craigslist.org",
     #  "https://oklahomacity.craigslist.org",
     #  "https://stillwater.craigslist.org",
     #  "https://texoma.craigslist.org",
     #  "https://tulsa.craigslist.org"
     # ],
     # "OR": [
     #  "https://bend.craigslist.org",
     #  "https://corvallis.craigslist.org",
     #  "https://eastoregon.craigslist.org",
     #  "https://eugene.craigslist.org",
     #  "https://klamath.craigslist.org",
     #  "https://medford.craigslist.org",
     #  "https://oregoncoast.craigslist.org",
     #  "https://portland.craigslist.org",
     #  "https://roseburg.craigslist.org",
     #  "https://salem.craigslist.org"
     # ],
     # "PA": [
     #  "https://altoona.craigslist.org",
     #  "https://chambersburg.craigslist.org",
     #  "https://erie.craigslist.org",
     #  "https://harrisburg.craigslist.org",
     #  "https://lancaster.craigslist.org",
     #  "https://allentown.craigslist.org",
     #  "https://meadville.craigslist.org",
     #  "https://philadelphia.craigslist.org",
     #  "https://pittsburgh.craigslist.org",
     #  "https://poconos.craigslist.org",
     #  "https://reading.craigslist.org",
     #  "https://scranton.craigslist.org",
     #  "https://pennstate.craigslist.org",
     #  "https://twintiers.craigslist.org",
     #  "https://williamsport.craigslist.org",
     #  "https://york.craigslist.org"
     # ],
     # "RI": [
     #  "https://providence.craigslist.org/"
     # ],
     # "SC": [
     #  "https://charleston.craigslist.org",
     #  "https://columbia.craigslist.org",
     #  "https://florencesc.craigslist.org",
     #  "https://greenville.craigslist.org",
     #  "https://hiltonhead.craigslist.org",
     #  "https://myrtlebeach.craigslist.org"
     # ],
     # "SD": [
     #  "https://nesd.craigslist.org",
     #  "https://csd.craigslist.org",
     #  "https://rapidcity.craigslist.org",
     #  "https://siouxfalls.craigslist.org",
     #  "https://sd.craigslist.org"
     # ],
     # "TN": [
     #  "https://chattanooga.craigslist.org",
     #  "https://clarksville.craigslist.org",
     #  "https://cookeville.craigslist.org",
     #  "https://jacksontn.craigslist.org",
     #  "https://knoxville.craigslist.org",
     #  "https://memphis.craigslist.org",
     #  "https://nashville.craigslist.org",
     #  "https://tricities.craigslist.org"
     # ],
     # "TX": [
     #  "https://abilene.craigslist.org",
     #  "https://amarillo.craigslist.org",
     #  "https://austin.craigslist.org",
     #  "https://beaumont.craigslist.org",
     #  "https://brownsville.craigslist.org",
     #  "https://collegestation.craigslist.org",
     #  "https://corpuschristi.craigslist.org",
     #  "https://dallas.craigslist.org",
     #  "https://nacogdoches.craigslist.org",
     #  "https://delrio.craigslist.org",
     #  "https://elpaso.craigslist.org",
     #  "https://galveston.craigslist.org",
     #  "https://houston.craigslist.org",
     #  "https://killeen.craigslist.org",
     #  "https://laredo.craigslist.org",
     #  "https://lubbock.craigslist.org",
     #  "https://mcallen.craigslist.org",
     #  "https://odessa.craigslist.org",
     #  "https://sanangelo.craigslist.org",
     #  "https://sanantonio.craigslist.org",
     #  "https://sanmarcos.craigslist.org",
     #  "https://bigbend.craigslist.org",
     #  "https://texarkana.craigslist.org",
     #  "https://texoma.craigslist.org",
     #  "https://easttexas.craigslist.org",
     #  "https://victoriatx.craigslist.org",
     #  "https://waco.craigslist.org",
     #  "https://wichitafalls.craigslist.org"
     # ],
     # "UT": [
     #  "https://logan.craigslist.org",
     #  "https://ogden.craigslist.org",
     #  "https://provo.craigslist.org",
     #  "https://saltlakecity.craigslist.org",
     #  "https://stgeorge.craigslist.org"
     # ],
     # "VA": [
     #  "https://charlottesville.craigslist.org",
     #  "https://danville.craigslist.org",
     #  "https://easternshore.craigslist.org",
     #  "https://fredericksburg.craigslist.org",
     #  "https://harrisonburg.craigslist.org",
     #  "https://lynchburg.craigslist.org",
     #  "https://blacksburg.craigslist.org",
     #  "https://norfolk.craigslist.org",
     #  "https://richmond.craigslist.org",
     #  "https://roanoke.craigslist.org",
     #  "https://swva.craigslist.org",
     #  "https://winchester.craigslist.org",
     #  "https://washingtondc.craigslist.org/nva/"
     # ],
     # "VT": [
     #  "https://vermont.craigslist.org/"
     # ],
     # "WA": [
     #  "https://bellingham.craigslist.org",
     #  "https://kpr.craigslist.org",
     #  "https://lewiston.craigslist.org",
     #  "https://moseslake.craigslist.org",
     #  "https://olympic.craigslist.org",
     #  "https://pullman.craigslist.org",
     #  "https://seattle.craigslist.org",
     #  "https://skagit.craigslist.org",
     #  "https://spokane.craigslist.org",
     #  "https://wenatchee.craigslist.org",
     #  "https://yakima.craigslist.org",
     #  "https://portland.craigslist.org/clk/"
     # ],
     # "WI": [
     #  "https://appleton.craigslist.org",
     #  "https://duluth.craigslist.org",
     #  "https://eauclaire.craigslist.org",
     #  "https://greenbay.craigslist.org",
     #  "https://janesville.craigslist.org",
     #  "https://racine.craigslist.org",
     #  "https://lacrosse.craigslist.org",
     #  "https://madison.craigslist.org",
     #  "https://milwaukee.craigslist.org",
     #  "https://northernwi.craigslist.org",
     #  "https://sheboygan.craigslist.org",
     #  "https://wausau.craigslist.org"
     # ],
     # "WV": [
     #  "https://charlestonwv.craigslist.org",
     #  "https://martinsburg.craigslist.org",
     #  "https://huntington.craigslist.org",
     #  "https://morgantown.craigslist.org",
     #  "https://wheeling.craigslist.org",
     #  "https://parkersburg.craigslist.org",
     #  "https://swv.craigslist.org",
     #  "https://wv.craigslist.org"
     # ],
     # "WY": [
     #  "https://wyoming.craigslist.org/"
     # ]
}

URLS_CAN = {    # 55 unique locations

     "barrie, ON": [
      "https://barrie.craigslist.ca"
     ],
     "belleville, ON": [
      "https://belleville.craigslist.ca"
     ],
     "brantford-woodstock": [
      "https://brantford.craigslist.ca"
     ],
     "calgary, AB": [
      "https://calgary.craigslist.ca"
     ],
     "cariboo, BC": [
      "https://cariboo.craigslist.ca"
     ],
     "chatham-kent, ON": [
      "https://chatham.craigslist.ca"
     ],
     "comox valley, BC": [
      "https://comoxvalley.craigslist.ca"
     ],
     "cornwall, ON": [
      "https://cornwall.craigslist.ca"
     ],
     "edmonton, AB": [
      "https://edmonton.craigslist.ca"
     ],
     "fraser valley, BC": [
      "https://abbotsford.craigslist.ca"
     ],
     "ft mcmurray, AB": [
      "https://ftmcmurray.craigslist.ca"
     ],
     "guelph, ON": [
      "https://guelph.craigslist.ca"
     ],
     "halifax, NS": [
      "https://halifax.craigslist.ca"
     ],
     "hamilton-burlington": [
      "https://hamilton.craigslist.ca"
     ],
     "kamloops, BC": [
      "https://kamloops.craigslist.ca"
     ],
     "kelowna / okanagan": [
      "https://kelowna.craigslist.ca"
     ],
     "kingston, ON": [
      "https://kingston.craigslist.ca"
     ],
     "kitchener-waterloo-cambridge": [
      "https://kitchener.craigslist.ca"
     ],
     "kootenays, BC": [
      "https://kootenays.craigslist.ca"
     ],
     "lethbridge, AB": [
      "https://lethbridge.craigslist.ca"
     ],
     "london, ON": [
      "https://londonon.craigslist.ca"
     ],
     "medicine hat, AB": [
      "https://hat.craigslist.ca"
     ],
     "montreal, QC": [
      "https://montreal.craigslist.ca"
     ],
     "nanaimo, BC": [
      "https://nanaimo.craigslist.ca"
     ],
     "new brunswick": [
      "https://newbrunswick.craigslist.ca"
     ],
     "niagara region": [
      "https://niagara.craigslist.ca"
     ],
     "ottawa-hull-gatineau": [
      "https://ottawa.craigslist.ca"
     ],
     "owen sound, ON": [
      "https://owensound.craigslist.ca"
     ],
     "peace river country": [
      "https://peace.craigslist.ca"
     ],
     "peterborough, ON": [
      "https://peterborough.craigslist.ca"
     ],
     "prince edward island": [
      "https://pei.craigslist.ca"
     ],
     "prince george, BC": [
      "https://princegeorge.craigslist.ca"
     ],
     "quebec city": [
      "https://quebec.craigslist.ca"
     ],
     "red deer, AB": [
      "https://reddeer.craigslist.ca"
     ],
     "regina, SK": [
      "https://regina.craigslist.ca"
     ],
     "saguenay, QC": [
      "https://saguenay.craigslist.ca"
     ],
     "sarnia, ON": [
      "https://sarnia.craigslist.ca"
     ],
     "saskatoon, SK": [
      "https://saskatoon.craigslist.ca"
     ],
     "sault ste marie, ON": [
      "https://soo.craigslist.ca"
     ],
     "sherbrooke, QC": [
      "https://sherbrooke.craigslist.ca"
     ],
     "skeena-bulkley": [
      "https://skeena.craigslist.ca"
     ],
     "st john's, NL": [
      "https://newfoundland.craigslist.ca"
     ],
     "sudbury, ON": [
      "https://sudbury.craigslist.ca"
     ],
     "sunshine coast, BC": [
      "https://sunshine.craigslist.ca"
     ],
     "territories": [
      "https://territories.craigslist.ca"
     ],
     "thunder bay, ON": [
      "https://thunderbay.craigslist.ca"
     ],
     "toronto": [
      "https://toronto.craigslist.ca"
     ],
     "trois-rivieres, QC": [
      "https://troisrivieres.craigslist.ca"
     ],
     "vancouver, BC": [
      "https://vancouver.craigslist.ca"
     ],
     "victoria, BC": [
      "https://victoria.craigslist.ca"
     ],
     "whistler / squamish": [
      "https://whistler.craigslist.ca"
     ],
     "whitehorse, YT": [
      "https://whitehorse.craigslist.ca"
     ],
     "windsor, ON": [
      "https://windsor.craigslist.ca"
     ],
     "winnipeg, MB": [
      "https://winnipeg.craigslist.ca"
     ],
     "yellowknife, NT": [
      "https://yellowknife.craigslist.ca"
     ]
}

URLS_UK = {     #27 unique locations
     "aberdeen": [
      "https://aberdeen.craigslist.co.uk"
     ],
     "bath, UK": [
      "https://bath.craigslist.co.uk"
     ],
     "belfast": [
      "https://belfast.craigslist.co.uk"
     ],
     "birmingham / west mids": [
      "https://birmingham.craigslist.co.uk"
     ],
     "brighton": [
      "https://brighton.craigslist.co.uk"
     ],
     "bristol": [
      "https://bristol.craigslist.co.uk"
     ],
     "cambridge, UK": [
      "https://cambridge.craigslist.co.uk"
     ],
     "cardiff / wales": [
      "https://cardiff.craigslist.co.uk"
     ],
     "coventry, UK": [
      "https://coventry.craigslist.co.uk"
     ],
     "derby, UK": [
      "https://derby.craigslist.co.uk"
     ],
     "devon & cornwall": [
      "https://devon.craigslist.co.uk"
     ],
     "dundee": [
      "https://dundee.craigslist.co.uk"
     ],
     "east anglia": [
      "https://norwich.craigslist.co.uk"
     ],
     "east midlands": [
      "https://eastmids.craigslist.co.uk"
     ],
     "edinburgh": [
      "https://edinburgh.craigslist.co.uk"
     ],
     "essex, UK": [
      "https://essex.craigslist.co.uk"
     ],
     "glasgow": [
      "https://glasgow.craigslist.co.uk"
     ],
     "hampshire": [
      "https://hampshire.craigslist.co.uk"
     ],
     "kent, UK": [
      "https://kent.craigslist.co.uk"
     ],
     "leeds": [
      "https://leeds.craigslist.co.uk"
     ],
     "liverpool": [
      "https://liverpool.craigslist.co.uk"
     ],
     "london, UK": [
      "https://london.craigslist.co.uk"
     ],
     "manchester, UK": [
      "https://manchester.craigslist.co.uk"
     ],
     "newcastle / NE england": [
      "https://newcastle.craigslist.co.uk"
     ],
     "nottingham, UK": [
      "https://nottingham.craigslist.co.uk"
     ],
     "oxford, UK": [
      "https://oxford.craigslist.co.uk"
     ],
     "sheffield": [
      "https://sheffield.craigslist.co.uk"
     ]
}
